### ISSUE TITLE
主页/和博客/blog一片空白报错，评论和订阅点击没反应

### ISSUE THREAD

**Issue by oozry12** [CaliCastle/cali.so#17]
经过几个小时反复删库试验，第一次搭建成功是可以进入主页，正常输出内容的。

![762`TJE42`B4GRQTZ`BC2HI](https://github.com/CaliCastle/cali.so/assets/1807379/7a1044b1-4e18-4458-b9a7-986c6e5a45ee)

一旦在`/studio` 新建一个文章post后，主页/和博客/blog一片空白报错
```
Application error: a client-side exception has occurred (see the browser console for more information).
Digest: 89999947
```
![V1Z(BH6%IP6~6U~9_P88PBC](https://github.com/CaliCastle/cali.so/assets/1807379/4e4586f0-e32e-4277-9695-fd0e629e3a8a)

![X{@SD HAS4PI1RS5V{) @0H](https://github.com/CaliCastle/cali.so/assets/1807379/1ad6d78c-3b1e-47b9-a420-4e4737943b1a)

Vercel后台报错

```
TypeError: Cannot read properties of null (reading 'join')
    at BlogPostCard (/var/task/.next/server/chunks/9574.js:239:70)
    at T (/var/task/.next/server/chunks/2546.js:9012:13)
    at Xa (/var/task/.next/server/chunks/2546.js:9117:21)
    at Array.toJSON (/var/task/.next/server/chunks/2546.js:8931:20)
    at stringify (<anonymous>)
    at hb (/var/task/.next/server/chunks/2546.js:9327:9)
    at eb (/var/task/.next/server/chunks/2546.js:9226:29)
    at Timeout._onTimeout (/var/task/.next/server/chunks/2546.js:9062:16)
    at listOnTimeout (node:internal/timers:569:17)
    at process.processTimers (node:internal/timers:512:7)
[Error: An error occurred in the Server Components render. The specific message is omitted in production builds to avoid leaking sensitive details. A digest property is included on this error instance which may provide additional details about the nature of the error.] {
  digest: '89999947'
}
```

`/studio`  `/admin`  `/guestbook`  `/about`  显示页面正常，但评论和订阅点击没反应，后台也没看到新增数据

**Comment by CaliCastle** [comment]
@oozry12 我猜是你没有加 category 导致的，试试同步到最新的 [commit](https://github.com/CaliCastle/cali.so/commit/0d27b98d88ba3bdc80dee45f2292d23754262c78) 看看有没有修复

**Comment by oozry12** [comment]
大佬，试了最新的源码。还是报错，呜呜
```
TypeError: Cannot read properties of null (reading 'toFixed')
    at BlogPostCard (/var/task/.next/server/chunks/9574.js:263:65)
    at T (/var/task/.next/server/chunks/2546.js:9012:13)
    at Xa (/var/task/.next/server/chunks/2546.js:9117:21)
    at Array.toJSON (/var/task/.next/server/chunks/2546.js:8931:20)
    at stringify (<anonymous>)
    at hb (/var/task/.next/server/chunks/2546.js:9327:9)
    at eb (/var/task/.next/server/chunks/2546.js:9226:29)
    at Timeout._onTimeout (/var/task/.next/server/chunks/2546.js:9062:16)
    at listOnTimeout (node:internal/timers:569:17)
    at process.processTimers (node:internal/timers:512:7)
[Error: An error occurred in the Server Components render. The specific message is omitted in production builds to avoid leaking sensitive details. A digest property is included on this error instance which may provide additional details about the nature of the error.] {
  digest: '411632288'
}

```

**Comment by oozry12** [comment]
本地调试报错
![image](https://github.com/CaliCastle/cali.so/assets/1807379/a07e535d-1e96-4a12-9ee6-614d35e3aa43)
```
Unhandled Runtime Error
Error: Cannot read properties of null (reading 'toFixed')
```

**Comment by CaliCastle** [comment]
@oozry12 你是不是没点击生成 reading time...

**Comment by oozry12** [comment]
> @oozry12 你是不是没点击生成 reading time...

点击哪里？看了教程，好像没有这个步骤

**Comment by CaliCastle** [comment]
@oozry12 你在写文章的地方，滑动到底下，reading time 必须按一下，否则没有值。

![Tower r7EnZQsQ@2x](https://github.com/CaliCastle/cali.so/assets/10830749/09c06ece-d608-41e8-8e38-77c705270f3b)

**Comment by oozry12** [comment]
感谢大佬的耐心~~~~原来问题在这里，一直以为后台发文章只要标题和正文重用就好，果然是细节控。以上的报错原来是`category` `reading time`  没加。惯性思维害死人，一般以为必填项都有 `*` 或者直接发布报错。好吧，再次为不认真读题惭愧。
