### ISSUE TITLE
管理 - 评论 页面 构建报错

### ISSUE THREAD

**Issue by CCKNBC** [CaliCastle/cali.so#45]
管理 - 评论 页面 构建报错

```bash
<!--StartFragment-->
build: error: function curdate() does not exist
--
22:44:55.115 | build:     at /vercel/path0/.next/server/chunks/6657.js:9:28989
22:44:55.115 | build:     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
22:44:55.115 | build:     at async y (/vercel/path0/.next/server/app/admin/comments/page.js:1:4995) {

<!--EndFragment-->
```

```bash
<!--StartFragment-->
build: error: function curdate() does not exist
--
22:44:55.119 | build:     at /vercel/path0/.next/server/chunks/6657.js:9:28989
22:44:55.119 | build:     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
22:44:55.119 | build:     at async y (/vercel/path0/.next/server/app/admin/comments/page.js:1:4995) {

<!--EndFragment-->

```

**Comment by CaliCastle** [comment]
已在最新 commit 中修复
